### ISSUE TITLE
Customizing container name in the sign-in modal

### ISSUE THREAD

**Issue by dsanghan** [AgileBits/AgileCloudSDK#31]
Thanks for the fantastic SDK. 

One question, I noticed on this [screenshot](https://tooagile-wpengine.netdna-ssl.com/wp-content/uploads/2016/01/Mac6iCloudAuth.png) that 1Password is somehow changing the "Sign in to [Container ID]" to Sign in to [Custom Name/Container Name]" on the CloudKit login screen. How would I go about doing that?

**Comment by kevinbhayes** [comment]
@dsanghan sorry about the very late reply. This must have slipped by. Apple substitutes that name based on the the name of the app published in the Mac App Store that uses the same container.
